<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>46613fc8-2d74-407e-a369-60f30cfe89e9</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Scalar.AspNetCore" Version="2.1.18" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BugTicketingSystem.BL\BugTicketingSystem.BL.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Options\" />
		<Folder Include="MiddleWares\" />
		<Folder Include="Filters\" />
	</ItemGroup>

</Project>
