// <auto-generated />
using System;
using BugTicketingSystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugTicketingSystem.DAL.Migrations
{
    [DbContext(typeof(BugTicketingContext))]
    partial class BugTicketingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BugTicketingSystem.DAL.Bug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Bugs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("328ebc19-b6f1-4193-ae06-bcbc19105ba4"),
                            Description = "When Using Seeding, Error You Must Use Async Seeding Also",
                            ProjectId = new Guid("1c017e23-6987-4d3b-911f-d3cf432a1c19"),
                            Status = "Solved",
                            Title = "Error In Using Seeding"
                        },
                        new
                        {
                            Id = new Guid("a546459d-089c-41b4-9a44-2629babaec06"),
                            Description = "Error In Signing In Using Auth",
                            ProjectId = new Guid("80fa2674-074a-4c48-8b6c-b63eb7ba60f1"),
                            Status = "Open",
                            Title = "Error In login"
                        },
                        new
                        {
                            Id = new Guid("ce66d99b-a171-445d-b2a7-30fc399412ff"),
                            Description = "When Using Paymob, An Error Occurred",
                            ProjectId = new Guid("b8e4ce6b-3606-4535-882a-3ceaf55b6808"),
                            Status = "Solved",
                            Title = "Error In Payment"
                        });
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.FileAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BugId");

                    b.ToTable("FileAttachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2cdbc40a-b617-4858-98bd-71edd758ee68"),
                            BugId = new Guid("328ebc19-b6f1-4193-ae06-bcbc19105ba4"),
                            FileName = "C# Code",
                            FilePath = "/uploads/file.sln",
                            UploadedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a289b995-a053-4318-8555-a5a6d9e5f75d"),
                            BugId = new Guid("a546459d-089c-41b4-9a44-2629babaec06"),
                            FileName = "Error ScreenShot",
                            FilePath = "/uploads/error_screenshot.png",
                            UploadedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e3ba3e0f-d2f5-406a-8fd8-70e9eca99e50"),
                            BugId = new Guid("ce66d99b-a171-445d-b2a7-30fc399412ff"),
                            FileName = "Error ScreenShot of Paymob",
                            FilePath = "/uploads/error_screenshot2.png",
                            UploadedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c017e23-6987-4d3b-911f-d3cf432a1c19"),
                            Description = "Examination System For Students To Evaluate their Level of Understanding Each Subject They Studied",
                            Name = "Examination System"
                        },
                        new
                        {
                            Id = new Guid("80fa2674-074a-4c48-8b6c-b63eb7ba60f1"),
                            Description = "E-Commerce Website to Practise On Angular And NodeJs",
                            Name = "E-Commerce Website"
                        },
                        new
                        {
                            Id = new Guid("b8e4ce6b-3606-4535-882a-3ceaf55b6808"),
                            Description = "E-Commerce Website to Practise On Angular And Asp.Net Using Apis",
                            Name = "E-Commerce Website2"
                        });
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a94a3ec6-77da-47b2-8428-bcbf372a3676"),
                            RoleName = "Tester"
                        },
                        new
                        {
                            Id = new Guid("dc435455-5ae0-43ab-919b-3029b64fb488"),
                            RoleName = "Developer"
                        },
                        new
                        {
                            Id = new Guid("f8b4285f-300e-4cd7-930c-f6f290faea0f"),
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59915d5a-e035-4da7-aa76-b767ae1844d6"),
                            EmailAddress = "basem@gmail.com",
                            FullName = "Basem Attia Elsayed",
                            Password = "Hasehed_Password_2"
                        },
                        new
                        {
                            Id = new Guid("bb31e5e5-85a9-4d06-9fac-6b3cb7cd495d"),
                            EmailAddress = "karim@gmail.com",
                            FullName = "Karim Mohamed Helmy",
                            Password = "Hasehed_Password_234"
                        },
                        new
                        {
                            Id = new Guid("e63d04ce-c434-428d-866a-aff44a00916c"),
                            EmailAddress = "mohamed@gmail.com",
                            FullName = "Mohamed ElSayed Tabei",
                            Password = "Hasehed_Password_235"
                        });
                });

            modelBuilder.Entity("BugUser", b =>
                {
                    b.Property<Guid>("BugsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BugsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("BugUser");

                    b.HasData(
                        new
                        {
                            BugsId = new Guid("328ebc19-b6f1-4193-ae06-bcbc19105ba4"),
                            UsersId = new Guid("59915d5a-e035-4da7-aa76-b767ae1844d6")
                        },
                        new
                        {
                            BugsId = new Guid("ce66d99b-a171-445d-b2a7-30fc399412ff"),
                            UsersId = new Guid("59915d5a-e035-4da7-aa76-b767ae1844d6")
                        },
                        new
                        {
                            BugsId = new Guid("328ebc19-b6f1-4193-ae06-bcbc19105ba4"),
                            UsersId = new Guid("bb31e5e5-85a9-4d06-9fac-6b3cb7cd495d")
                        },
                        new
                        {
                            BugsId = new Guid("a546459d-089c-41b4-9a44-2629babaec06"),
                            UsersId = new Guid("bb31e5e5-85a9-4d06-9fac-6b3cb7cd495d")
                        },
                        new
                        {
                            BugsId = new Guid("ce66d99b-a171-445d-b2a7-30fc399412ff"),
                            UsersId = new Guid("e63d04ce-c434-428d-866a-aff44a00916c")
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("a94a3ec6-77da-47b2-8428-bcbf372a3676"),
                            UsersId = new Guid("59915d5a-e035-4da7-aa76-b767ae1844d6")
                        },
                        new
                        {
                            RolesId = new Guid("dc435455-5ae0-43ab-919b-3029b64fb488"),
                            UsersId = new Guid("59915d5a-e035-4da7-aa76-b767ae1844d6")
                        },
                        new
                        {
                            RolesId = new Guid("f8b4285f-300e-4cd7-930c-f6f290faea0f"),
                            UsersId = new Guid("bb31e5e5-85a9-4d06-9fac-6b3cb7cd495d")
                        },
                        new
                        {
                            RolesId = new Guid("f8b4285f-300e-4cd7-930c-f6f290faea0f"),
                            UsersId = new Guid("e63d04ce-c434-428d-866a-aff44a00916c")
                        },
                        new
                        {
                            RolesId = new Guid("dc435455-5ae0-43ab-919b-3029b64fb488"),
                            UsersId = new Guid("e63d04ce-c434-428d-866a-aff44a00916c")
                        });
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.Bug", b =>
                {
                    b.HasOne("BugTicketingSystem.DAL.Project", "Project")
                        .WithMany("Bugs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.FileAttachment", b =>
                {
                    b.HasOne("BugTicketingSystem.DAL.Bug", "Bug")
                        .WithMany("FileAttachments")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bug");
                });

            modelBuilder.Entity("BugUser", b =>
                {
                    b.HasOne("BugTicketingSystem.DAL.Bug", null)
                        .WithMany()
                        .HasForeignKey("BugsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTicketingSystem.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("BugTicketingSystem.DAL.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugTicketingSystem.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.Bug", b =>
                {
                    b.Navigation("FileAttachments");
                });

            modelBuilder.Entity("BugTicketingSystem.DAL.Project", b =>
                {
                    b.Navigation("Bugs");
                });
#pragma warning restore 612, 618
        }
    }
}
